import speech_recognition as sr
import pyttsx3
import pywhatkit
import datetime


Listener = sr.Recognizer()
engine = pyttsx3.init()
def talk(text):
    engine.say(text)
    engine.runAndWait()

def take_command():
    try:
        with sr.Microphone() as source:
            print("listening")
            talk("waiting for your command")
            voice = Listener.listen(source)
            command = Listener.recognize_google(voice)
            command = command.lower()
            
            return command
        
    except : 
       print("there is error")

list_of_negative_sentance = ["no","not","bad","evil","None","No one","Nobody","Nothing","Neither","Nowhere","Never", "hate"]
    
list_for_finding = ["find", "who","search","what","how"]

#dictionary_of_numbers = {'one':1,'two':2,'three':3,'four':4,'five':5,'six':6,'seven':7,'eight':8,'nine':9,'ten':10}

def run_mark():
    command = take_command()
    if command!= None:
        if "mark" not in command:
            talk("Key to start me is 'My Name'")
            if "what is your name" in command :
                talk("My master gave me the name 'Mark', and I like my name as it means 'GOD OF WAR'")
        else:
            if "who made you" in command:
                talk("i was made by Aniruddha Kumar, my master")
            elif "play"and"favourite" in command :
                talk("playing Neoni") 
                pywhatkit.playonyt("https://www.youtube.com/watch?v=Dhu3VSj-qnk&list=PLIqoFJDfJD4OeFQBFbrJv9ZqA9ulSM87o")
            elif "hey mark you there" in command:
                talk("yes i am here, master")
            elif "check sentence" in command : 
                talk("checking sentence")
                command = command.replace("mark","")
                command = command.replace("check sentence","")
                for items_in_list_of_negative_sentance in list_of_negative_sentance:
                    if items_in_list_of_negative_sentance in command :
                        talk("this is a negative sentence")
                        print(command)
                        break
                else:
                    talk("this is a positive sentence")
                    print(command)     
            elif "play" in command and "favourite" not in command:
                song = command.replace("play", "")
                talk("playing"+ song)
                pywhatkit.playonyt(song)
            elif "time" in command:
                command = command.replace("mark", "")
                time = datetime.datetime.now().strftime("%I:%M %p")
                talk ("current time is" + time)
            elif "are you stupid" in command: 
                talk("Maybe I am, but you are the one who made me and i am still learning")
            elif "send whatsapp" in command:
                pywhatkit.sendwhatmsg("+919002754591", "This message is generated by Mark",10,33
                )          
                talk("sending message to Alok")
            elif "how are you doing" in command :
                talk("I am doing just fine, and i hope you are also doing just fine, my master")
            elif "stop" in command:
                talk("your wish my command")
                quit(run_mark)
            elif "birthday" in command:
                talk("Yes, today is Pushpendra birthday")
                talk("Do you want to wish him")
            elif "wish" in command:
                talk("okay then I will wish him on your behalf")
                talk("Happy Birthday to You , Happy Birthday to You, Happy Birthday Dear Pushpender, Happy Birthday to You. From good friends and true, From old friends and new, May good luck go with you,And happiness too.")
            elif "question" in command:
                for items_of_list_for_finding in list_for_finding:
                    if items_of_list_for_finding in command :
                        pywhatkit.search(command)
                        talk("finding")
                        print("searching")
                else : talk("I am sorry to disappoint you, but your question is not making sense, master ")
            else :
                talk("i am not understanding your command, Master")
                print(command)
        
    else: 
        talk("no command given, Master")

while True:
    run_mark()  
     